[versions]
kotlinx-datetime = "v0.7.1"
kotlinx-serialization-json = "1.9.0"
kotlinx-coroutines = "1.10.2"
adventure = "4.25.0"
paper-api = "1.21.10-R0.1-SNAPSHOT"
luckperms = "5.5"
ascend = "2025.8-64943c6"
logback = "1.5.21"

[libraries]
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
kotlinx-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
adventure-api = { group = "net.kyori", name = "adventure-api", version.ref = "adventure" }
adventure-text-minimessage = { group = "net.kyori", name = "adventure-text-minimessage", version.ref = "adventure" }
adventure-text-serializer-legacy = { group = "net.kyori", name = "adventure-text-serializer-legacy", version.ref = "adventure" }
adventure-text-serializer-plain = { group = "net.kyori", name = "adventure-text-serializer-plain", version.ref = "adventure" }
luckperms = { group = "net.luckperms", name = "api", version.ref = "luckperms"}
ascend = { group = "dev.fruxz", name = "ascend", version.ref = "ascend" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
paper-api = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper-api" }

[bundles]
kotlinx-ecosystem = ["kotlinx-datetime", "kotlinx-serialization-json", "kotlinx-coroutines"]
adventure = ["adventure-api", "adventure-text-minimessage", "adventure-text-serializer-legacy", "adventure-text-serializer-plain"]